### ISSUE TITLE
issue with (-34) Protocol error: this is generally the result of an incompatibility between this client an the accessed server. still exists after workaround

### ISSUE THREAD

**Issue by CynicalWilson** [Devolutions/doc#1019]
Followed all proposed workaround steps, but creating an ssh tunnel (as a gateway jumphost) still fails with the same error message. 
I enabled all algorythm supports, skipped variable change as well as aded the PowerShell scripts.
RDM Version : 2023.3.35.0 64-bit  . Same issue has been present now for many releases.

(-34) Protocol error: this is generally the result of an incompatibility between this client an the accessed server.

 ---
#### Document Details

⚠ *Do not edit this section. It is required for docs.devolutions.net ➟ GitHub issue linking.*

* Content: [SSH algorithm support](https://docs.devolutions.net/kb/devolutions-powershell/remote-desktop-manager/ssh-algorithm-support/)
* Content Source: [/content/en/kb/devolutions-powershell/remote-desktop-manager/ssh-algorithm-support.md](https://github.com/Devolutions/doc/tree/master/docs/content/en/kb/devolutions-powershell/remote-desktop-manager/ssh-algorithm-support.md)
* Service: **<b>Devolutions</b> Knowledge Base**

**Comment by JeanSebastienSimard** [comment]
Hello, 

Thank you for reaching out to the Devolutions Documentation team.

For inquiries requiring specific technical assistance tailored to your unique context, we kindly suggest that you write an email to our dedicated support team at [service@devolutions.net](mailto:service@devolutions.net). Our technical experts are equipped to provide detailed and personalized solutions to address your concerns.

When composing your email, please include as much relevant information as possible about your situation. This will enable our support team to better understand your needs and respond promptly with the most accurate guidance.

Thank you for helping us enhance the Devolutions experience!

The Devolutions Documentation team
