### ISSUE TITLE
Possible Error on Get-LAPSADPassword command 

### ISSUE THREAD

**Issue by aricade** [Devolutions/doc#1020]
[Enter feedback here]

Line that has:

`        $MyPassword=Get-LapsADPassword -Identity $PARAMETER1$ -AsPlainText`

As `$PARAMETER1$` in your example is `".\admin"` and not the computername

Should be:

`        $MyPassword=Get-LapsADPassword -Identity $HOST$ -AsPlainText`

Or something that signifies the computername to `Get-LAPSAdPassword`.  Is `$HOST$` Correct variable name as it does not seem to work for me.

 ---
#### Document Details

⚠ *Do not edit this section. It is required for docs.devolutions.net ➟ GitHub issue linking.*

* Content: [Configure LAPS with a custom credentials entry](https://docs.devolutions.net/kb/remote-desktop-manager/how-to-articles/configure-laps-custom-credential-entry/)
* Content Source: [/content/en/kb/remote-desktop-manager/how-to-articles/configure-laps-custom-credential-entry.md](https://github.com/Devolutions/doc/tree/master/docs/content/en/kb/remote-desktop-manager/how-to-articles/configure-laps-custom-credential-entry.md)
* Service: **<b>Devolutions</b> Knowledge Base**

**Comment by JeanSebastienSimard** [comment]
Hello, 

Thank you for reaching out to the Devolutions Documentation team.


I've asked my support technician colleagues to look into your situation. I'll get back to you very shortly in this same thread.

Best regards,

The Devolutions Documentation team

**Comment by aricade** [comment]
BTW I got it working with:

`$MyPassword=Get-LapsADPassword -Identity $NAME$ -AsPlainText`

I suppose `$HOST$` should work as well depending on the value that it retrieves in RDM.

**Comment by erica-poirier** [comment]
That's right; it depends on the information stored in the RDP entry's Host property.  If it's the IP address or the FQDN of the server, I'm wondering if it's supported by Get-LapsADPassword cmdlet. 

If you'd like more help, you can open a case at [service@devolutions.net](mailto:service@devolutions.net)!

**Comment by aricade** [comment]
@erica-poirier  is there anyway to pass a Credential to Get-LapsAdPassword command?

E.g.

`
$Cred = New-Object System.Management.Automation.PSCredential ("username", $password)
$MyPassword=Get-LapsADPassword -Identity $NAME$ -AsPlainText -Credential $Cred  -DomainController $PARAMETER2$
`

Is there a way to lookup ones credentials in RDM and pass them to the powershell script? This is for the case where you may be operating from or to other AD Domains and your current logon that has the RDM client may not be native to the target Domain.

Off topic sorry.

**Comment by erica-poirier** [comment]
@aricade, sadly, I'm not aware of any method to pass credentials for your scenario in a Custom Credential entry to use LAPS as another user.

The following forum's message I posted mentioned that our developers haven't yet found how to achieve this.
https://forum.devolutions.net/topics/28828/login-using-laps-credentials#135326

They even gave up on it as no solution is available.

If you want us to revive this request, I recommend you post a new feature request with as many details as possible on our forum here.
https://forum.devolutions.net/forums/17/remote-desktop-manager--feature-request

Best regards,
