### ISSUE TITLE
Welcome page "page not found", options to change url not available

### ISSUE THREAD

**Issue by byman64** [Devolutions/doc#1036]
[Enter feedback here]

I cannot fix the welcome page url wrong.
Welcome works fine if I set English as language. When I set Italian I get "page not found"

I cannot find the option to change the url as reported in your documentation 
"https://docs.devolutions.net/kb/remote-desktop-manager/troubleshooting-articles/welcome-page/#:~:text=Under%20Administration%20in%20the%20ribbon,to%20your%20custom%20welcome%20page."

"Under Administration in the ribbon, choose Data Source Settings (System Settings) Then, in Applications, under the Welcome Page section, enter the URL that points to your custom welcome page"

My Remote Desktop Manager version : 2023.3.35.0 64-bit

Please let me know if you need more details

regards

 ---
#### Document Details

⚠ *Do not edit this section. It is required for docs.devolutions.net ➟ GitHub issue linking.*

* Content: [Welcome page](https://docs.devolutions.net/kb/remote-desktop-manager/troubleshooting-articles/welcome-page/)
* Content Source: [/content/en/kb/remote-desktop-manager/troubleshooting-articles/welcome-page.md](https://github.com/Devolutions/doc/tree/master/docs/content/en/kb/remote-desktop-manager/troubleshooting-articles/welcome-page.md)
* Service: **<b>Devolutions</b> Knowledge Base**

**Comment by JeanSebastienSimard** [comment]
Hello,

Thank you for reaching out to the Devolutions Documentation team.

This help topic is out of date, we are very sorry about that. Thank you for pointing this out to us, we will update the topic shortly.

With a Devolutions Server or SQL Server data source, you now need to go in the RDM ribbon in **_Administration – System Settings – Application Specific – Applications_**. Then, if you scroll down a bit, you should see the **_Welcome Page_** option. This of course assumes that you are an administrator and have access to the **_Administration_** tab of the ribbon.

For any other thoughts on specific product features or if you have any more questions, please email our support team at [service@devolutions.net](mailto:service@devolutions.net). Your input is invaluable to us.

Thank you for helping us enhance the Devolutions experience!

The Devolutions Documentation team

**Comment by JeanSebastienSimard** [comment]
Hello again, 

We have updated the topic page following your comments: [Welcome page](https://docs.devolutions.net/kb/remote-desktop-manager/troubleshooting-articles/welcome-page/).

We thank you again for your contribution.

Best regards, 

The Devolutions Documentation team

**Comment by byman64** [comment]
It's not so important but I really don't find where is this option.

I am not sure if I started from the right place. BTW
1# Here what I see from RDM ribbon in Administration.
This path are missing:  System Settings – Application Specific – Applications.
![image](https://github.com/Devolutions/doc/assets/2996260/0b331006-16a9-4fe5-bc16-afefae4e8c59)

2# Here what I see from settings, using search setting
![image](https://github.com/Devolutions/doc/assets/2996260/c2bef9ec-c3c8-47c0-8b6a-7d590c5d0bf4)

regards

**Comment by JeanSebastienSimard** [comment]
Hello,

It depends on your data source and other context-specific factors. That is why I highly suggest you to contact our support technicians at [service@devolutions.net](mailto:service@devolutions.net). They have the knowledge and expertise to properly and efficiently help you with your issue.

Best regards, 

Devolutions Documentation team
