### ISSUE TITLE
How can i import the earlier created local datasources into hub Personal?[Feedback]: 

### ISSUE THREAD

**Issue by mvdheide01** [Devolutions/doc#1087]
### Contact Details

marcel@strongdynamic.be

### Feedback

Hi,
I see that we can use the free Hub Personal but i cannot find how to import earlier created datasources
Marcel
 ---
#### Document Details

⚠ *Do not edit this section. It is required for docs.devolutions.net ➟ GitHub issue linking.*

* Content: [Devolutions Hub Personal](https://docs.devolutions.net/kb/hub-personal/)
* Content Source: [/content/en/kb/hub-personal/index.md](https://github.com/Devolutions/doc/tree/master/docs/content/en/kb/hub-personal/index.md)
* Service: **<b>Devolutions</b> Knowledge Base**

**Comment by JeanSebastienSimard** [comment]
Hello, 

I assume that you want to import existing data sources into Remote Desktop Manager? If so, you would need to import the data source configuration and entries separately. First, create a new data source and import the configuration of the existing data source (see [Export and import data sources configuration](https://docs.devolutions.net/kb/remote-desktop-manager/how-to-articles/import-export-data-sources-configuration/)). Then, import your entries (see [Export and import entries](https://docs.devolutions.net/kb/remote-desktop-manager/how-to-articles/export-import-entries/)) and/or vaults (see [Export and import vaults](https://docs.devolutions.net/kb/remote-desktop-manager/how-to-articles/export-import-vaults/)) into the newly configured data source.

If I misunderstood your initial question, the following help topics may help you: 
- [Import entries in Remote Desktop Manager](https://docs.devolutions.net/rdm/windows/commands/file/import/)
- [Import entries in Devolutions Hub Personal](https://docs.devolutions.net/kb/hub-personal/how-to-articles/import-export-data-hub-personal/)

For more help, please reach out to our support team at [service@devolutions.net](mailto:service@devolutions.net). Our technical experts are equipped to provide detailed and personalized solutions to address your issue.

Best regards,

The Devolutions Documentation team

**Comment by mvdheide01** [comment]
Hi,

Yes, that is what I found at the end to do but it cost me more than an hour to find this solution.
Maybe a good idea to make this a bit easier for people to follow because I also had to do 3 retries with the format of the export before it was accepted.

It worked perfect by the way.

Met hartelijke groet / kind regards,

Marcel van der Heide
Strong Dynamic

Eindhoutsebaan 56
2450 Meerhout
Belgium

***@***.***
www.strongdynamic.be

Mobile +32 (0)492 06 09 81


[image001.png]

On 12 Jan 2024, at 15:24, Jean-Sébastien Simard ***@***.***> wrote:



Hello,

I assume that you want to import existing data sources into Remote Desktop Manager? If so, you would need to import the data source configuration and entries separately. First, create a new data source and import the configuration of the existing data source (see Export and import data sources configuration<https://docs.devolutions.net/kb/remote-desktop-manager/how-to-articles/import-export-data-sources-configuration/>). Then, import your entries (see Export and import entries<https://docs.devolutions.net/kb/remote-desktop-manager/how-to-articles/export-import-entries/>) and/or vaults (see Export and import vaults<https://docs.devolutions.net/kb/remote-desktop-manager/how-to-articles/export-import-vaults/>) into the newly configured data source.

If I misunderstood your initial question, the following help topics may help you:

  *   Import entries in Remote Desktop Manager<https://docs.devolutions.net/rdm/windows/commands/file/import/>
  *   Import entries in Devolutions Hub Personal<https://docs.devolutions.net/kb/hub-personal/how-to-articles/import-export-data-hub-personal/>

For more help, please reach out to our support team at ***@***.******@***.***>. Our technical experts are equipped to provide detailed and personalized solutions to address your issue.

Best regards,

The Devolutions Documentation team

**Comment by JeanSebastienSimard** [comment]
Hello,

Thank you for your feedback, we'll see what we can do to make the process clearer in our documentation.

Best regards,

The Devolutions Documentation team
