### ISSUE TITLE
[Feedback]: Template creation

### ISSUE THREAD

**Issue by edulallo** [Devolutions/doc#1107]
### Contact Details

eduardo.lallo@hotmail.com

### Feedback

Dear, good morning,

I am writing to see if there is this option when creating a template or if you see it useful to add it in a future update.
I have been creating the Template option for some time, and I was looking for a way to unify the names of the entries, in this case the RDP.
For this I usually use in the place host, the variable $INFORMATION_MACHINE_NAME$, this information I take it from completing the Asset in the Network sector adding the host and the IP in this place.
After this data, for name I use two variables:

$INFORMATION_MACHINE_NAME$ - $INFORMATION_IP$.

And with this the name is completed with the host name and the IP.

However when creating the template I could not find a place where to leave automated that when I create a new RDP always in the name appears $INFORMATION_MACHINE_NAME$ - $INFORMATION_IP$.

And I find this option interesting, since in my case I use hostname+IP, but I am sure that there will be people, who use some other option with the name and maybe some part would like to be automated.

I await your comments to know if it is possible to do this and from where.

Thank you very much for your help.
![Uploading add rdp.png…]()

 ---
#### Document Details

⚠ *Do not edit this section. It is required for docs.devolutions.net ➟ GitHub issue linking.*

* Content: [Default settings](https://docs.devolutions.net/rdm/windows/commands/file/templates/default-settings/)
* Content Source: [/en/rdm/windows/commands/file/templates/default-settings.md](https://github.com/Devolutions/doc/tree/master/docs/en/rdm/windows/commands/file/templates/default-settings.md)
* Service: **&lt;b&gt;Remote Desktop&lt;/b&gt; Manager**

**Comment by JeanSebastienSimard** [comment]
Hello,

Thank you for reaching out to the Devolutions Documentation Team.

We have forwarded your issue to our support technicians, who will be opening a case for you. You can expect a response from them within 48 business hours.

Best regards,

The Devolutions Documentation Team
