### ISSUE TITLE
[Feedback]:Your downloads page is offline!

### ISSUE THREAD

**Issue by tunaycp** [Devolutions/doc#1229]
### Contact Details

tcantepe@gmail.com

### Feedback

[[Feedback]:Your downloads page is offline! (https://server.devolutions.net/home/download)]

 ---
#### Document Details

⚠ *Do not edit this section. It is required for docs.devolutions.net ➟ GitHub issue linking.*

* Content: [Installation](https://docs.devolutions.net/server/installation/)
* Content Source: [/content/en/server/installation/index.md](https://github.com/Devolutions/doc/tree/master/docs/content/en/server/installation/index.md)
* Service: **<b>Devolutions</b> Server**

**Comment by JeanSebastienSimard** [comment]
Hello, 

Thank you for reaching out to the Devolutions Documentation team!

I am sorry that you had trouble downloading our products. As of now, I can reach the Devolutions Server download page you linked in your previous message, and both download links work. You may have encountered a problem at the time, but I only tested it a few minutes ago.

If you are still unable to access the download page, please email our support technicians at [service@devolutions.net](mailto:service@devolutions.net). They have the knowledge and expertise to further assist you.

Best regards, 

The Devolutions Documentation Team
