### ISSUE TITLE
Don't see Secret Server as an option.

### ISSUE THREAD

**Issue by kelemvor33** [Devolutions/doc#1261]
### Contact Details

kelemvor@gmail.com

### Feedback

I have a Secret option but no Secret Server option.  Is this available in the Free version or only the Paid version?  If it's only in the Paid version, if you could add a note about that at the top of the screen, that'd be great.

Thanks.

 ---
#### Document Details

⚠ *Do not edit this section. It is required for docs.devolutions.net ➟ GitHub issue linking.*

* Content: [Secret server entry configuration](https://docs.devolutions.net/kb/remote-desktop-manager/how-to-articles/secret-server-entry-configuration/)
* Content Source: [/content/en/kb/remote-desktop-manager/how-to-articles/secret-server-entry-configuration.md](https://github.com/Devolutions/doc/tree/master/docs/content/en/kb/remote-desktop-manager/how-to-articles/secret-server-entry-configuration.md)
* Service: **<b>Devolutions</b> Knowledge Base**

**Comment by JeanSebastienSimard** [comment]
Hello, 

Thank you for your feedback! You are right, the Secret Server entry is only available with the paid version of Remote Desktop Manager. I have added a note at the top of the topic as you suggested: [Secret server entry configuration](https://docs.devolutions.net/kb/remote-desktop-manager/how-to-articles/secret-server-entry-configuration/).

Best regards, 

The Devolutions Documentation Team
