### ISSUE TITLE
[Feedback]: IMPORTING AN RDM ISSUE no files are coming up 

### ISSUE THREAD

**Issue by seanyskadoo** [Devolutions/doc#1288]
### Contact Details

s

### Feedback

[Enter feedback here]

 ---
#### Document Details

⚠ *Do not edit this section. It is required for docs.devolutions.net ➟ GitHub issue linking.*

* Content: [Import (.rdm)](https://docs.devolutions.net/rdm/commands/file/import/rdm/)
* Content Source: [/content/en/rdm/commands/file/import/rdm/index.md](https://github.com/Devolutions/doc/tree/master/docs/content/en/rdm/commands/file/import/rdm/index.md)
* Service: **<b>Remote Desktop</b> Manager**

**Comment by JeanPhilippeLessard** [comment]
Hello seanyskadoo,

Thank you for reaching out to the Devolutions Documentation Team.

For issues with specific product features, please email our support team at [service@devolutions.net](mailto:service@devolutions.net) as they have the knowledge and expertise to further assist you.

Best regards,

The Devolutions Documentation Team
