### ISSUE TITLE
Is is possible to user Remote desktop Manager and Azure Bastion in combination of IP-Based features of Azure Bastion 

### ISSUE THREAD

**Issue by mouquetneoledge** [Devolutions/doc#1304]
### Contact Details

mouquet@neoledge.com

### Feedback

Is is possible to user Remote desktop Manager and Azure Bastion in combination of IP-Based features of Azure Bastion ?

I tried to replace the Hose by the IP of the VM i try to contact, but i have the following message:
Azure Bastion or Connection mode doesn't offer connection through ip client

I have well activate ip based connection feature on Azure Bastion, and can connect sucessfuly to the destination vm from Azure Portal with Azure Bastion

 ---
#### Document Details

⚠ *Do not edit this section. It is required for docs.devolutions.net ➟ GitHub issue linking.*

* Content: [Configure an Azure Bastion entry in Remote Desktop Manager](https://docs.devolutions.net/kb/remote-desktop-manager/how-to-articles/configure-azure-bastion-entry/)
* Content Source: [/content/en/kb/remote-desktop-manager/how-to-articles/configure-azure-bastion-entry.md](https://github.com/Devolutions/doc/tree/master/docs/content/en/kb/remote-desktop-manager/how-to-articles/configure-azure-bastion-entry.md)
* Service: **<b>Devolutions</b> Knowledge Base**

**Comment by JeanSebastienSimard** [comment]
Hello, 

Thank you for reaching out to the Devolutions Documentation Team.

We have forwarded your issue to our support technicians, who have the knowledge and expertise to further assist you. They will be opening a case for you. You can expect a response from them within 48 business hours.

Best regards, 

The Devolutions Documentation Team
