### ISSUE TITLE
[Feedback]: None of the metods works...

### ISSUE THREAD

**Issue by vdias** [Devolutions/doc#1313]
### Contact Details

vdias.pt@gmail.com

### Feedback

 none of the methods worked...

Using a 49 inch monitor, and using RDP is a nightmare... cannot change screen size on any RDP sessions...
 ---
#### Document Details

⚠ *Do not edit this section. It is required for docs.devolutions.net ➟ GitHub issue linking.*

* Content: [High DPI issues](https://docs.devolutions.net/kb/remote-desktop-manager/troubleshooting-articles/high-dpi-issue/)
* Content Source: [/content/en/kb/remote-desktop-manager/troubleshooting-articles/high-dpi-issue.md](https://github.com/Devolutions/doc/tree/master/docs/content/en/kb/remote-desktop-manager/troubleshooting-articles/high-dpi-issue.md)
* Service: **<b>Devolutions</b> Knowledge Base**

**Comment by JeanSebastienSimard** [comment]
Hello, 

Thank you for reaching out to the Devolutions Documentation Team.

We have forwarded your issue to our support technicians, who have the knowledge and expertise to further assist you. They will be opening a case for you. You can expect a response from them within 48 business hours.

Best regards, 

The Devolutions Documentation Team
