### ISSUE TITLE
[Feedback]: 

### ISSUE THREAD

**Issue by Anon4343** [Devolutions/doc#1320]
### Contact Details

j.coccia@outlook.com

### Feedback

Document does not describe how to recover from already having this installed and still being prompted to install it.

Error: Installation failed. The Microsoft Edge Webview2 Runtime is already installed for the system.

 ---
#### Document Details

⚠ *Do not edit this section. It is required for docs.devolutions.net ➟ GitHub issue linking.*

* Content: [Download Microsoft Edge Chromium](https://docs.devolutions.net/kb/remote-desktop-manager/knowledge-base/download-microsoft-edge-chromium/)
* Content Source: [/content/en/kb/remote-desktop-manager/knowledge-base/download-microsoft-edge-chromium.md](https://github.com/Devolutions/doc/tree/master/docs/content/en/kb/remote-desktop-manager/knowledge-base/download-microsoft-edge-chromium.md)
* Service: **<b>Devolutions</b> Knowledge Base**

**Comment by JeanSebastienSimard** [comment]
Hello, 

Thank you for reaching out to the Devolutions Documentation Team.

We have forwarded your issue to our support technicians, who have the knowledge and expertise to further assist you. They will be opening a case for you. You can expect a response from them within 48 business hours.

Best regards, 

The Devolutions Documentation Team

**Comment by JeanSebastienSimard** [comment]
Hello,

Following your recent feedback and the exchange you had with our support technicians, we have updated the [Download Microsoft Edge Chromium](https://docs.devolutions.net/kb/remote-desktop-manager/knowledge-base/download-microsoft-edge-chromium/) topic you pointed out. We also have created a new troubleshooting topic addressing the particular issue you were having and its solution. Here it is: [Microsoft Edge WebView2 Runtime installation troubleshooting](https://docs.devolutions.net/kb/remote-desktop-manager/troubleshooting-articles/microsoft-edge-webview2-runtime-installation-troubleshooting/).

Thank you once again for your constructive feedback.

Best regards, 

The Devolutions Documentation Team

**Comment by Anon4343** [comment]
Nice. Just one correction. The deleting the registry key and installing the bootstrapper version didn’t resolve the issue. Deleting the registry key and installing the offline version did. My guess is that the offline version is mor eof a full install where the bootstrapper is closer to a repair.

**Comment by JeanSebastienSimard** [comment]
Hello,

Thank you for this clarification.

Best regards, 

The Devolutions Documentation Team
