### ISSUE TITLE
rdm 2024.1.5 [Feedback]: 

### ISSUE THREAD

**Issue by lavinnyv** [Devolutions/doc#1334]
### Contact Details

lavinnyv@gmail.com

### Feedback

mac m1 with sonoma. i'm trying to send a typing macro to 3 ssh sessions that i'm logged in to. i'm testing out the broadcasting feature. i work with some other apps like this that i create typing macros/scripts/commands on the left and then i'm able to double click them or whatever is the command to execute them and then it sends that typing command to the ssh shells that i'm logged into.

i've attached a screengrab with what i set up.

it seems like this is how it should run in rdm as well. even down to when i right click on the clear typing macro, it says execute. and there is an execute button above on the ribbon. but when i double click/right click exexcute/hit the execute button. nothing happens in my shells.

am i missing something with this function?

thanks

![Screenshot 2024-03-12 at 12 09 04 PM](https://github.com/Devolutions/doc/assets/41637908/3999a296-ddf1-4b18-8886-22011eb31f9a)

**Comment by JeanSebastienSimard** [comment]
Hello, 

Thank you for reaching out to the Devolutions Documentation Team.

We have forwarded your issue to our support technicians, who have the knowledge and expertise to further assist you. They will be opening a case for you. You can expect a response from them within 48 business hours.

Best regards, 

The Devolutions Documentation Team
