### ISSUE TITLE
CSV samples

### ISSUE THREAD

**Issue by JoeBrunsTR** [Devolutions/doc#1346]
### Contact Details

joe.bruns@thomsonreuters.com

### Feedback

Would be great if you could provide some CSV file examples (used for importing into RDM) for Windows and Linux that would include parent folders and entries that go inside.

 ---
#### Document Details

⚠ *Do not edit this section. It is required for docs.devolutions.net ➟ GitHub issue linking.*

* Content: [CSV import strategies and file format](https://docs.devolutions.net/rdm/commands/file/import/generic-csv-wizard/strategies-file-format/)
* Content Source: [/content/en/rdm/commands/file/import/generic-csv-wizard/strategies-file-format.md](https://github.com/Devolutions/doc/tree/master/docs/content/en/rdm/commands/file/import/generic-csv-wizard/strategies-file-format.md)
* Service: **<b>Remote Desktop</b> Manager**

**Comment by JeanSebastienSimard** [comment]
Hello, 

We have updated our [CSV import strategies and file format](https://docs.devolutions.net/rdm/commands/file/import/generic-csv-wizard/strategies-file-format/) article to add information related to the four CSV types (Session, Credential, Information, Template), as explained by our colleague James in [this Devolutions Forum thread](https://forum.devolutions.net/topics/41477/request-for-sample-csv-file-for-generic-csv-wizard) you participated in. We have also added the CSV template example from the same forum thread at the end of the article.

We will now be closing this GitHub issue, but do not hesitate to write back on our forum or to [contact our support technicians](mailto:service@devolutions.net) for anything else.

Best regards, 

The Devolutions Documentation Team
