### ISSUE TITLE
[Feedback]: syntax highlight

### ISSUE THREAD

**Issue by soheilamiri** [Devolutions/doc#1354]
### Contact Details

soheil.amiri@live.com 

### Feedback

[Enter feedback here]

 ---
#### Document Details

⚠ *Do not edit this section. It is required for docs.devolutions.net ➟ GitHub issue linking.*

* Content: [Syntax highlighting](https://docs.devolutions.net/kb/remote-desktop-manager/knowledge-base/syntax-highlighting/)
* Content Source: [/content/en/kb/remote-desktop-manager/knowledge-base/syntax-highlighting.md](https://github.com/Devolutions/doc/tree/master/docs/content/en/kb/remote-desktop-manager/knowledge-base/syntax-highlighting.md)
* Service: **<b>Devolutions</b> Knowledge Base**
Hello dear
is it possible to add multiple keywork in  section? i did not find any guide how to separate multiple vocabulary.

**Comment by JeanSebastienSimard** [comment]
Hello,

Thank your for reaching out to the Devolutions Documentation Team!

I've spoken with our development team, and they've suggested that simply separating your keywords with a line break (Enter key) will work. I've updated our documentation to reflect this information: [Syntax highlighting](https://docs.devolutions.net/kb/remote-desktop-manager/knowledge-base/syntax-highlighting/).

Should you have any further questions or require additional assistance, please contact our support technicians directly at [service@devolutions.net](mailto:service@devolutions.net). Your feedback is invaluable to us!

Best regards, 

The Devolutions Documentation Team
