### ISSUE TITLE
[Feedback]: 

### ISSUE THREAD

**Issue by kriso980** [Devolutions/doc#1370]
### Contact Details

crisg17@hotmail.com

### Feedback

[Enter feedback here]

 ---
#### Document Details

⚠ *Do not edit this section. It is required for docs.devolutions.net ➟ GitHub issue linking.*

* Content: [Advanced data source](https://docs.devolutions.net/rdm/data-sources/data-sources-types/advanced-data-sources/)
* Content Source: [/content/en/rdm/data-sources/data-sources-types/advanced-data-sources/index.md](https://github.com/Devolutions/doc/tree/master/docs/content/en/rdm/data-sources/data-sources-types/advanced-data-sources/index.md)
* Service: **<b>Remote Desktop</b> Manager**

**Comment by JeanPhilippeLessard** [comment]
Hello kriso980,

Your feedback seems to be missing, so I will be closing this issue. Please feel free to share your feedback here or open a new issue.


Best regards, 

The Devolutions Documentation Team
