### ISSUE TITLE
[Feedback]: Entry Image Management Issue

### ISSUE THREAD

**Issue by mist-arch** [Devolutions/doc#1379]
### Feedback

[Enter feedback here]

 ---
#### Document Details

⚠ *Do not edit this section. It is required for docs.devolutions.net ➟ GitHub issue linking.*

* Content: [Images](https://docs.devolutions.net/rdm/commands/administration/settings/images/)
* Content Source: [/content/en/rdm/commands/administration/settings/images.md](https://github.com/Devolutions/doc/tree/master/docs/content/en/rdm/commands/administration/settings/images.md)
* Service: **<b>Remote Desktop</b> Manager**

Hello,

I've installed rdm on my Arch Linux, everything is fine but one. Entry Image Management. 
It feels like rdm can't import anything because of permissions, i don't know, perhaps something else ?

Here the menu :
![image](https://github.com/Devolutions/doc/assets/151822170/b67f7e7d-0c00-4911-9f04-a871d74784b8)

I can import :
![image](https://github.com/Devolutions/doc/assets/151822170/1679cec6-95df-4a86-9999-a25bee756232)

But when i refresh or close or edit, the icon disappear for no visual reason :
![image](https://github.com/Devolutions/doc/assets/151822170/fa183544-af6d-4276-bd6f-bdf251391382)

**Comment by JeanSebastienSimard** [comment]
Hello, 

Thank you for reaching out to the Devolutions Documentation Team.

We have forwarded your issue to our support technicians, who have the knowledge and expertise to further assist you. They will be opening a case for you. You can expect a response from them within 48 business hours.

Best regards, 

The Devolutions Documentation Team
