### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by jnl002** [Devolutions/doc#1393]
### Contact Details

noyoudonotneedit@no.com

### Feedback

No suggestions yet. Just feedback on a great job. I've been using it for over two years and it has what I need. Thanks for the great work.

That said, the hoops required to leave feedback in this forum leave some to be desired The team that setup this feedback system needs to take lessons for your software dev team. It should have taken me 15 seconds, not 5 minutes.

**Comment by JeanSebastienSimard** [comment]
Hello, 

Firstly, we sincerely appreciate you taking the time to share your feedback with us. Rest assured, it has been forwarded to our development team!

We understand there were some challenges you faced when attempting to provide feedback on our documentation. We apologize for any inconvenience this may have caused. To clarify, a GitHub account is necessary to leave feedback about our documentation pages, which might have contributed to the delay. 

Our users frequently provide suggestions to enhance specific documentation pages, whether by proposing additions, deletions, or updates to the content. Often, they go a step further by editing the documentation directly, leaving us with the task of reviewing their contributions. This collaborative approach is incredibly beneficial, and it's precisely why having a GitHub account is necessary. It enables a streamlined process for us to receive and incorporate your valuable insights and edits.

We recognize that some users might also seek assistance from our support technicians during this process. For such instances, we kindly request an email address to facilitate opening a support case, ensuring a seamless experience.

For a more direct dialogue with our support team, development team, and the broader Devolutions community, we highly recommend joining the [Devolutions Forum](https://forum.devolutions.net/). Accessing the Devolutions Forum requires only your Devolutions account, making it a straightforward way to engage with us and share your insights.

We will be closing this feedback thread. Should you have any comments or suggestions regarding our documentation, please do not hesitate to reach out again through this thread or by utilizing the _**Give us feedback**_ button featuring the GitHub logo located at the bottom of any documentation page.

We are truly thankful for your feedback. Rest assured, it will be warmly received by our development team.

Best regards, 

The Devolutions Documentation Team

**Comment by JeanSebastienSimard** [comment]
Hello,

Firstly, we sincerely appreciate you taking the time to share your feedback with us. Rest assured, it has been forwarded to our development team!

We understand there were some challenges you faced when attempting to provide feedback on our documentation. We apologize for any inconvenience this may have caused. To clarify, a GitHub account is necessary to leave feedback about our documentation pages, which might have contributed to the delay.

Our users frequently provide suggestions to enhance specific documentation pages, whether by proposing additions, deletions, or updates to the content. Often, they go a step further by editing the documentation directly, leaving us with the task of reviewing their contributions. This collaborative approach is incredibly beneficial, and it's precisely why having a GitHub account is necessary. It enables a streamlined process for us to receive and incorporate your valuable insights and edits.

We recognize that some users might also seek assistance from our support technicians during this process. For such instances, we kindly request an email address to facilitate opening a support case, ensuring a seamless experience.

For a more direct dialogue with our support team, development team, and the broader Devolutions community, we highly recommend joining the [Devolutions Forum](https://forum.devolutions.net/). Accessing the Devolutions Forum requires only your Devolutions account, making it a straightforward way to engage with us and share your insights.

We will be closing this feedback thread for the time being. Should you have any comments or suggestions regarding our documentation, please do not hesitate to reach out again through this thread or by utilizing the Give us feedback button featuring the GitHub logo located at the bottom of any documentation page.

We are truly thankful for your feedback. It will be warmly received by our development team.

Best regards,

The Devolutions Documentation Team
