### ISSUE TITLE
Play list and favorites of Remote Desktop Manager

### ISSUE THREAD

**Issue by gitthonandrhub** [Devolutions/doc#1398]
### Contact Details

andreas.thon@koerber.com

### Feedback

Hello,

today I found the play list feature. I think the purpose of it is to collect RDM entries to a list and start them with one click. It's not a featrue that I missed but it's good to now.

But for me this feature has the same problem as like as the favorites. I can add items or I can mark items as favorite for faster access, but I miss additional settings for such entries. In our company we manage a lot of remote desktop connections in RDM and we use personalized accounts to login. So to open a connection I have to use "Open with parameters" -> "Open (Select Credentials)". 

It would be a nice and helpful feature to add credentials information to a play list entry or a favorite, so that this credentials assignment is only active for this entry in my private vault or for my favorite entry, not for all users.

Best Regards

 ---
#### Document Details

⚠ *Do not edit this section. It is required for docs.devolutions.net ➟ GitHub issue linking.*

* Content: [Play List](https://docs.devolutions.net/rdm/commands/edit/edit/play-list/)
* Content Source: [/content/en/rdm/commands/edit/edit/play-list/index.md](https://github.com/Devolutions/doc/tree/master/docs/content/en/rdm/commands/edit/edit/play-list/index.md)
* Service: **<b>Remote Desktop</b> Manager**

**Comment by JeanSebastienSimard** [comment]
Hello, 

Thank you for reaching out to the Devolutions Documentation Team. We greatly value your feedback! 

For feature requests, we strongly encourage you to post in our [Devolutions Forum, under the **_Remote Desktop Manager - Feature Request_** section](https://forum.devolutions.net/forums/17/remote-desktop-manager--feature-request). These posts are always answered by one of our support technicians, our developers, or even our CEO! For any other questions about our products, please contact our support team at [service@devolutions.net|(mailto:service@devolutions.net).

Best regards, 

The Devolutions Documentation Team
