### ISSUE TITLE
[Feedback]: Mobile device management configuration from Remote Desktop Manager

### ISSUE THREAD

**Issue by boivinx7** [Devolutions/doc#1499]
### Contact Details

boivinx7@gmail.com

### Feedback

Does not seem to be exporting anything
Also, a lot of the menus have different names now

 ---
#### Document Details

⚠ *Do not edit this section. It is required for docs.devolutions.net ➟ GitHub issue linking.*

* Content: [Mobile device management configuration from Remote Desktop Manager](https://docs.devolutions.net/fr/kb/remote-desktop-manager-mobile/ios/how-to-articles/mobile-device-management-configuration/)
* Content Source: [/content/fr/kb/remote-desktop-manager-mobile/ios/how-to-articles/mobile-device-management-configuration.md](https://github.com/Devolutions/doc/tree/master/docs/content/fr/kb/remote-desktop-manager-mobile/ios/how-to-articles/mobile-device-management-configuration.md)
* Service: **<b>Devolutions</b> Knowledge Base**

**Comment by JeanPhilippeLessard** [comment]
Hello boivinx7, 

Thank you for reaching out to the Devolutions Documentation Team.

We have forwarded your issue to our support technicians, who have the knowledge and expertise to further assist you. They will be opening a case for you. You can expect a response from them within 48 business hours.

Best regards, 

The Devolutions Documentation Team
