### ISSUE TITLE
[Feedback]: 

### ISSUE THREAD

**Issue by wazzajjdjhqsidj** [Devolutions/doc#1573]
### Contact Details

faresbensalem1005@gmail.com

### Feedback

[Enter feedback here]

 ---
#### Document Details

⚠ *Do not edit this section. It is required for docs.devolutions.net ➟ GitHub issue linking.*

* Content: [Remote Desktop Manager](https://docs.devolutions.net/rdm/overview/what-is-rdm/)
* Content Source: [/content/en/rdm/overview/what-is-rdm.md](https://github.com/Devolutions/doc/tree/master/docs/content/en/rdm/overview/what-is-rdm.md)
* Service: **<b>Remote Desktop</b> Manager**

**Comment by JeanPhilippeLessard** [comment]
Hello, 

Thank you for reaching out to the Devolutions Documentation Team.

Your feedback seems to be missing, so we will be closing this issue. Please feel free to share your feedback here or open a new issue.

Best regards,

The Devolutions Documentation Team
