### ISSUE TITLE
[Feedback]: Not able to connect to Azure Bastion via RDM

### ISSUE THREAD

**Issue by mkuhn75** [Devolutions/doc#1591]
### Contact Details

marc.kuhn@everyware.ch

### Feedback

Hi Team
i try to configure connecting to a Azure Bastion via RDM. Our version is 2023.2.18.0 64-bit. We have multiple Azure subscriptions in place, which might be the issue.

When i try to connect to the Azure Bastion, i receive this message (see attachment)

![bastion](https://github.com/Devolutions/doc/assets/102892127/25d96a69-6e68-4541-92ef-9ef4e70ee78b)

Login via Azure Portal and Azure Bastion is working just fine.

Do you have any solution for this?

Thanks and best regards,
Marc
 ---
#### Document Details

⚠ *Do not edit this section. It is required for docs.devolutions.net ➟ GitHub issue linking.*

* Content: [Configure an Azure Bastion entry in Remote Desktop Manager](https://docs.devolutions.net/kb/remote-desktop-manager/how-to-articles/configure-azure-bastion-entry/)
* Content Source: [/content/en/kb/remote-desktop-manager/how-to-articles/configure-azure-bastion-entry.md](https://github.com/Devolutions/doc/tree/master/docs/content/en/kb/remote-desktop-manager/how-to-articles/configure-azure-bastion-entry.md)
* Service: **<b>Devolutions</b> Knowledge `Base**```

**Comment by JeanSebastienSimard** [comment]
Hello, 

Thank you for reaching out to the Devolutions Documentation Team.

We have forwarded your issue to our support technicians, who have the knowledge and expertise to further assist you. They will be opening a case for you. You can expect a response from them within 48 business hours.

Best regards, 

The Devolutions Documentation Team
