### ISSUE TITLE
Startup performance settings moved

### ISSUE THREAD

**Issue by ctleng76** [Devolutions/doc#1605]
### Contact Details

jason.baron@sbcglobal.net

### Feedback

This knowledgebase article shows how to access the "Hardware Acceleration" and "Optimize UI performance" options for improving startup performance.  The screenshot used as an example is from an older version of the application.  These options are no longer located in the "Advanced" settings menu .  They have been moved to a new menu selection called "Performance".  Otherwise, the settings suggestion is spot on.  After changing these settings, the application opens in 10 seconds vs almost a minute.

Thanks

 ---
#### Document Details

⚠ *Do not edit this section. It is required for docs.devolutions.net ➟ GitHub issue linking.*

* Content: [Startup performance](https://docs.devolutions.net/kb/remote-desktop-manager/troubleshooting-articles/startup-performance/)
* Content Source: [/content/en/kb/remote-desktop-manager/troubleshooting-articles/startup-performance.md](https://github.com/Devolutions/doc/tree/master/docs/content/en/kb/remote-desktop-manager/troubleshooting-articles/startup-performance.md)
* Service: **<b>Devolutions</b> Knowledge Base**
*

**Comment by JeanSebastienSimard** [comment]
Hello,

We're pleased to hear that our documentation page was helpful in resolving your issue. Your feedback has been shared with the entire team.

Thank you for pointing out the discrepancies regarding the ***Hardware acceleration*** and ***Optimize UI performance*** settings. You are correct; some options previously in the ***Advanced*** section have been reorganized into other sections for greater clarity. We have updated the documentation accordingly and have made other minor updates.

Best regards,

The Devolutions Documentation Team
