### ISSUE TITLE
[Feedback]:  These screen images and instruction do not match the program UI

### ISSUE THREAD

**Issue by ddaniels-andmore** [Devolutions/doc#1665]
### Contact Details

someguy@emai.com

### Feedback

These screen images and instruction do not match the program UI

 ---
#### Document Details

⚠ *Do not edit this section. It is required for docs.devolutions.net ➟ GitHub issue linking.*

* Content: [Configure a secure gateway](https://docs.devolutions.net/kb/remote-desktop-manager/how-to-articles/configure-secure-gateway/)
* Content Source: [/content/en/kb/remote-desktop-manager/how-to-articles/configure-secure-gateway.md](https://github.com/Devolutions/doc/tree/master/docs/content/en/kb/remote-desktop-manager/how-to-articles/configure-secure-gateway.md)
* Service: **<b>Devolutions</b> Knowledge Base**

**Comment by JeanSebastienSimard** [comment]
Hello, 

Thank you for bringing this to our attention. You are correct; the screenshots are from the older Remote Desktop Manager UI. All of them, except for the one in step 3, still function the same way.

We will look into updating this KB soon. Thank you for your input.

Best regards,

The Devolutions Documentation Team
