### ISSUE TITLE
[Feedback]: There is no option in the Linux version for restore

### ISSUE THREAD

**Issue by aitaix** [Devolutions/doc#1667]
### Contact Details

aitaix9@gmail.com

### Feedback

There is no option in the linux version  "Click on File – Backup – Restore"

 ---
#### Document Details

⚠ *Do not edit this section. It is required for docs.devolutions.net ➟ GitHub issue linking.*

* Content: [Backup restore](https://docs.devolutions.net/rdm/commands/file/backup/backup-restore/)
* Content Source: [/content/en/rdm/commands/file/backup/backup-restore.md](https://github.com/Devolutions/doc/tree/master/docs/content/en/rdm/commands/file/backup/backup-restore.md)
* Service: **<b>Remote Desktop</b> Manager**

**Comment by JeanSebastienSimard** [comment]
Hello,

Thank you for contacting the Devolutions Documentation team.

We are actively working on Remote Desktop Manager documentation for Linux. For alternative backup solutions for your specific case on Linux, we recommend reaching out to our support technicians at [service@devolutions.net](mailto:service@devolutions.net). They have the expertise to assist you with any inquiries.

Best regards,

The Devolutions Documentation Team
