### ISSUE TITLE
[Feedback]: 

### ISSUE THREAD

**Issue by GTAdoum** [Devolutions/doc#1700]
### Contact Details

dominic@msibureautique.ca

### Feedback

How to enter exactly the information?  I keep trying different way, but only an error is returned, so how to know if it is a problem with the server or the way I enter the information?

 ---
#### Document Details

⚠ *Do not edit this section. It is required for docs.devolutions.net ➟ GitHub issue linking.*

* Content: [Configure a client data source](https://docs.devolutions.net/server/kb/how-to-articles/configure-client-data-source/)
* Content Source: [/content/en/server/kb/how-to-articles/configure-client-data-source.md](https://github.com/Devolutions/doc/tree/master/docs/content/en/server/kb/how-to-articles/configure-client-data-source.md)
* Service: **<b>Devolutions</b> Server**

**Comment by JeanSebastienSimard** [comment]
Hello, 

Thank you for reaching out to the Devolutions Documentation Team.

We have forwarded your issue to our support technicians, who have the knowledge and expertise to further assist you. They will be opening a case for you. You can expect a response from them within 48 business hours.

Best regards, 

The Devolutions Documentation Team
