### ISSUE TITLE
[Feedback]: "inherited" custom fields

### ISSUE THREAD

**Issue by pgluszcz** [Devolutions/doc#1704]
### Contact Details

pglu@tlen.pl

### Feedback

[Enter feedback here]
Is it possible to "inherit" / "refere" to the custom field from "parrent object" ?
Imagin I have a server folder and many entries inside it. I would like to have custom filed for management VLAN (ILO) and data VLAN and the last part of server's IP address (at least 3 custom fields to be "inherited").
I can create a template group based on this server folder and its entries.
When I create an :object: based on this template group all I would like to change is some names and custom fields in the folder and do not touch the entries - entries' arguments would be filed based on "inherited" custom fields and names from folder.
Maybe this feature already exists, but I ca't find it in the documentation nor application. :-(
 ---
#### Document Details

⚠ *Do not edit this section. It is required for docs.devolutions.net ➟ GitHub issue linking.*

* Content: [Custom fields](https://docs.devolutions.net/rdm/concepts/intermediate-concepts/custom-fields/)
* Content Source: [/content/en/rdm/concepts/intermediate-concepts/custom-fields.md](https://github.com/Devolutions/doc/tree/master/docs/content/en/rdm/concepts/intermediate-concepts/custom-fields.md)
* Service: **<b>Remote Desktop</b> Manager**

**Comment by JeanSebastienSimard** [comment]
Hello, 

Thank you for reaching out to the Devolutions Documentation Team.

We have forwarded your issue to our support technicians, who have the knowledge and expertise to further assist you. They will be opening a case for you. You can expect a response from them within 48 business hours.

Best regards, 

The Devolutions Documentation Team
