### ISSUE TITLE
[Feedback]: iDRAC 7 issue in RemoteDesktopManager 

### ISSUE THREAD

**Issue by SuperioRuss** [Devolutions/doc#1705]
### Contact Details

msteksov@asiacement.ru

### Feedback

Hello!
After updating from RDM version 2023.3.39.0 where iDRAC connectivity WORKS to ANY newer version (now latest I tried is 2024.1.30) I cannot connect to my DELL servers with iDRAC.
![Screenshot_27](https://github.com/Devolutions/doc/assets/171560526/0dae4bf8-2d7f-4b7e-a8f0-56d719c0005f)
On the latest version I receive a (rather typical) error (see above). However I login with same credentials and settings successfully in 2023 versions. I modify none when updating RDM to 2024 version and all iDRAC connections stop working. I install 2023 version back and all works.
My servers use Dell iDRAC 7.
If it's possible please fix this issue as I am forced to use old version whilst the latest version would be preferable.
 ---
#### Document Details

⚠ *Do not edit this section. It is required for docs.devolutions.net ➟ GitHub issue linking.*

* Content: [Getting started](https://docs.devolutions.net/rdm/getting-started/)
* Content Source: [/content/en/rdm/getting-started/index.md](https://github.com/Devolutions/doc/tree/master/docs/content/en/rdm/getting-started/index.md)
* Service: **<b>Remote Desktop</b> Manager**

**Comment by JeanSebastienSimard** [comment]
Hello, 

Thank you for reaching out to the Devolutions Documentation Team.

We have forwarded your issue to our support technicians, who have the knowledge and expertise to further assist you. They will be opening a case for you. You can expect a response from them within 48 business hours.

Best regards, 

The Devolutions Documentation Team
