### ISSUE TITLE
[Feedback]: Remote Desktop Manager - RDP Hung/Frozen Sessions

### ISSUE THREAD

**Issue by joseemil** [Devolutions/doc#1764]
### Contact Details

emiljosecs@gmail.com

### Feedback

[Enter feedback here]

Hi Team,

Good Day

I have been using Remote Desktop Manager for years, and for the past couple of weeks, I have frequently faced an issue that the RDP sessions are getting hung or frozen. This prevents me from doing any further action within Remote Desktop Manager, and the only option is to end the session from the task manager and launch the application again. However, within a short period of time, I will end up with the same issue.

As a troubleshooting step, I have tried below. But none of them helped.

1. Repair the Application

2. Uninstall the applications, remove all the associated files from the system and user profiles, and reinstall the application from scratch

3. Always keep the application on the latest version by performing the version upgrade

 ---
#### Document Details

⚠ *Do not edit this section. It is required for docs.devolutions.net ➟ GitHub issue linking.*

* Content: [Remote Desktop Manager](https://docs.devolutions.net/rdm/overview/what-is-rdm/)
* Content Source: [/content/en/rdm/overview/what-is-rdm.md](https://github.com/Devolutions/doc/tree/master/docs/content/en/rdm/overview/what-is-rdm.md)
* Service: **<b>Remote Desktop</b> Manager**

**Comment by JeanSebastienSimard** [comment]
Hello, 

Thank you for reaching out to the Devolutions Documentation Team.

We have forwarded your issue to our support technicians, who have the knowledge and expertise to further assist you. They will be opening a case for you. You can expect a response from them within 48 business hours.

Best regards, 

The Devolutions Documentation Team
