### ISSUE TITLE
[Feedback]:  More documentation 

### ISSUE THREAD

**Issue by Reid1996** [Devolutions/doc#1951]
### Contact Details

propyroamv@gmail.com

### Feedback

Documentation isn't update, i try the example of New-Hubentry end it's didn't work.

 [Devolutions.Generated.Enums.ConnectionType] don't exist

[Devolutions.Hub.CryptoUtils.Models.PSDecryptedEntry] it's replace by this : [Devolutions.Hub.PowerShell.Entities.Hub.PSDecryptedEntry] but is not documented and the reason of why.

[Devolutions.Generated.Models.Connection] don't exist
[Devolutions.Generated.Enums.ConnectionType] don't exist
[Devolutions.Generated.Enums.CredentialResolverConnectionType] don't exist

 ---
#### Document Details

⚠ *Do not edit this section. It is required for docs.devolutions.net ➟ GitHub issue linking.*

* Content: [Devolutions.PowerShell module objects](https://docs.devolutions.net/powershell/hub-powershell/objects/)
* Content Source: [/content/en/powershell/hub-powershell/objects.md](https://github.com/Devolutions/doc/tree/master/docs/content/en/powershell/hub-powershell/objects.md)
* Service: **Devolutions PowerShell**

**Comment by JeanPhilippeLessard** [comment]
Hello Reid1996, 

Thank you for your feedback.

We are looking into the PowerShell modules you've mentioned and we will update the topic to reflect what we just discussed and let you know when we have done so.

Best regards, 

The Devolutions Documentation Team
