### ISSUE TITLE
[Feedback]: Step 5 code does not match the note describing what variables are used

### ISSUE THREAD

**Issue by lenzc-pasco-wa** [Devolutions/doc#2003]
### Contact Details

lenzc@pasco-wa.gov

### Feedback

[Enter feedback here]
Step 5's note says that the $HOST$ variable is used for the -ComputerName switch, but the switch used in the code is -Identity. The parameter provided to that switch is $PARAMETER1$, which points to the username set in the parameters tab. The -Identity switch should have $HOST$ provided. $PARAMETER1$ should be assigned to $Result.Username= if $MyPassword.Username does not exist. With Windows LAPS, the username is also stored in AD and can be queried via Powershell.
 ---
#### Document Details

⚠ *Do not edit this section. It is required for docs.devolutions.net ➟ GitHub issue linking.*

* Content: [Configure LAPS with a custom credentials entry](https://docs.devolutions.net/rdm/kb/rdm-windows/how-to-articles/configure-laps-custom-credential-entry/)
* Content Source: [/content/en/rdm/kb/rdm-windows/how-to-articles/configure-laps-custom-credential-entry.md](https://github.com/Devolutions/doc/tree/master/docs/content/en/rdm/kb/rdm-windows/how-to-articles/configure-laps-custom-credential-entry.md)
* Service: **<b>Remote Desktop</b> Manager**

**Comment by JeanSebastienSimard** [comment]
Hello,

Thank you for bringing this to our attention!

We agree that the current KB article could be clearer and should be updated with new and improved information. After consulting with one of our support technicians, I've opened a support case on your behalf. Our team has the expertise to assist you further and will also use this opportunity to enhance our documentation. You can expect a response from them within 48 business hours.

Best regards,

Devolutions Documentation Team
