### ISSUE TITLE
[Feedback]: TOTP

### ISSUE THREAD

**Issue by asgerfrisgard** [Devolutions/doc#2026]
### Contact Details

asger.frisgaard@bestseller.com

### Feedback

TOTP is prompting fine in the app, but I'm not asked for it when I use the Powershell module

 ---
#### Document Details

⚠ *Do not edit this section. It is required for docs.devolutions.net ➟ GitHub issue linking.*

* Content: [Authenticator (TOTP)](https://docs.devolutions.net/rdm/data-sources/multi-factor-authentication/authenticator-totp/)
* Content Source: [/content/en/rdm/data-sources/multi-factor-authentication/authenticator-totp.md](https://github.com/Devolutions/doc/tree/master/docs/content/en/rdm/data-sources/multi-factor-authentication/authenticator-totp.md)
* Service: **<b>Remote Desktop</b> Manager**

**Comment by JeanPhilippeLessard** [comment]
Hello, 

Thank you for reaching out to the Devolutions Documentation Team.

We have forwarded your issue to our support technicians, who have the knowledge and expertise to further assist you. They will be opening a case for you. You can expect a response from them within 48 business hours.

Best regards, 

The Devolutions Documentation Team
