### ISSUE TITLE
[Feedback]: 

### ISSUE THREAD

**Issue by mufa988** [Devolutions/doc#2048]
### Contact Details

mufa988@icloud.com

### Feedback

[Enter feedback here]

 ---
#### Document Details

⚠ *Do not edit this section. It is required for docs.devolutions.net ➟ GitHub issue linking.*

* Content: [Remote Desktop Manager macOS](https://docs.devolutions.net/rdm/mac/overview/what-is-rdm/)
* Content Source: [/en/rdm/mac/overview/what-is-rdm.md](https://github.com/Devolutions/doc/tree/master/docs/en/rdm/mac/overview/what-is-rdm.md)
* Service: **&lt;b&gt;Remote Desktop&lt;/b&gt; Manager**

**Comment by JeanSebastienSimard** [comment]
Hello, 

Thank you for reaching out to the Devolutions Documentation Team.

Your feedback seems to be missing, so we will be closing this issue. Please feel free to share your feedback here or open a new issue.

Best regards,

The Devolutions Documentation Team
