### ISSUE TITLE
Keywords are useless if not searched for in standard search

### ISSUE THREAD

**Issue by stevecharon** [Devolutions/doc#575]
Searching is kind of cumbersome if you have keywords configured and always have to rely on the advanced search
Keywords are useless if not searched for in standard search
at least they should be markable to be searched against

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.devolutions.net ➟ GitHub issue linking.*

* Content: [Search](https://docs.devolutions.net/server/web-interface/search/)
* Content Source: [/en/server/web-interface/search.md](https://github.com/Devolutions/doc/tree/master/docs/en/server/web-interface/search.md)
* Service: **Devolutions Server**

**Comment by JeanSebastienSimard** [comment]
Hello,

Thank you for your feedback! To share thoughts on specific product features, please email our support team at [service@devolutions.net](mailto:service@devolutions.net). Your input is invaluable to us.

Best regards,

Devolutions Documentation team
