### ISSUE TITLE
A missing step, I think?

### ISSUE THREAD

**Issue by dcdorsey777** [Devolutions/doc#910]
In the article "Configure SSO authentication with Microsoft Azure", there may be a missing step after or during step 6.  I don't know if this is a new feature in Azure provisioning or not, but at the bottom of the Azure portal page that is screen-shotted in step 6, there is a slider labeled "Provisioning Status".  It seems to be Off by default.  Until I switched it to On, the Provisioning status in the Hub continued to show "SSO not set up.  After switching it to On, the rest of the process proceeded normally.

BTW, the rest of the procedure was REALLY well documented, thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.devolutions.net ➟ GitHub issue linking.*

* Content: [Configure SSO authentication with Microsoft Azure](https://docs.devolutions.net/hub/getting-started/get-started-sso-hub-business/configure-sso-authentication-microsoft-azure/)
* Content Source: [/en/hub/getting-started/get-started-sso-hub-business/configure-sso-authentication-microsoft-azure.md](https://github.com/Devolutions/doc/tree/master/docs/en/hub/getting-started/get-started-sso-hub-business/configure-sso-authentication-microsoft-azure.md)
* Service: **Devolutions Hub**

**Comment by JeanSebastienSimard** [comment]
Hello again, 

Following your comments, we have merged the **_Adding a user/group_** section into the [**_Provisioning configuration_**](https://docs.devolutions.net/hub/getting-started/get-started-sso-hub-business/configure-sso-authentication-microsoft-azure/#provisioning-configuration) section. I think it makes the instructions much clearer. Thank you again for your comments, it helped a lot!

I will now close this issue. If you need anything else, please leave another feedback or email our support team at [service@devolutions.net](mailto:service@devolutions.net).

Best regards, 

Devolutions Documentation team
