### ISSUE TITLE
Upgrading to 2023.3.32.0 prevents use of the free version

### ISSUE THREAD

**Issue by Billiamh** [Devolutions/doc#918]
I updated to 2023.3.32.0 as prompted by the application today. I was not able to use the application and it indicated that no enterprise license was found. I had to uninstall and reinstall a previous version to regain use of the application.

 ---
#### Document Details

⚠ *Do not edit this section. It is required for docs.devolutions.net ➟ GitHub issue linking.*

* Content: [Remote Desktop Manager](https://docs.devolutions.net/kb/remote-desktop-manager/)
* Content Source: [/content/en/kb/remote-desktop-manager/index.md](https://github.com/Devolutions/doc/tree/master/docs/content/en/kb/remote-desktop-manager/index.md)
* Service: **<b>Devolutions</b> Knowledge Base**

**Comment by JeanSebastienSimard** [comment]
Hello,

Thank you for your feedback! For questions and to share thoughts on specific product features, please email our support team at [service@devolutions.net](mailto:service@devolutions.net). Your input is invaluable to us.

Best regards,

Devolutions Documentation team
