### ISSUE TITLE
Microsoft LAPS vs Windows LAPS

### ISSUE THREAD

**Issue by dmonarch1973** [Devolutions/doc#929]
I recently configured Windows LAPS, which is the successor to Microsoft LAPS, and attempted to Configure LAPS with a custom credential entry KB found at https://docs.devolutions.net/kb/remote-desktop-manager/how-to-articles/configure-laps-custom-credential-entry/ , however, what I ran in to is an error when I try and connect by grabbing the LAPS encrypted password, then piping that back into the password for the local LAPS Admin account. I verified that the account I was logged in to my workstation, that I run RDM from, had the correct permissions to read the encrypted passwords, but have not had any luck. Do you know if this KB is verified to work under the new LAPS app and if not, are there plans to update the guide?

 ---
#### Document Details

⚠ *Do not edit this section. It is required for docs.devolutions.net ➟ GitHub issue linking.*

* Content: [Configure LAPS with a custom credential entry](https://docs.devolutions.net/kb/remote-desktop-manager/how-to-articles/configure-laps-custom-credential-entry/)
* Content Source: [/content/en/kb/remote-desktop-manager/how-to-articles/configure-laps-custom-credential-entry.md](https://github.com/Devolutions/doc/tree/master/docs/content/en/kb/remote-desktop-manager/how-to-articles/configure-laps-custom-credential-entry.md)
* Service: **<b>Devolutions</b> Knowledge Base**

**Comment by JeanSebastienSimard** [comment]
Hello,

Thank you for your feedback! As you mentioned, the KB is indeed outdated. It does not work with the new LAPS. We are actively working on updating the KB as we speak. Thank you for bringing this to our attention!

In the meantime, I have asked our team to provide me with the updated PowerShell script. Here it is: 

```
Import-Module LAPS -ErrorAction SilentlyContinue

$isImport = Get-Module -List LAPS

if ($isImport)
{
    try 
        {
         $null2 = [System.DirectoryServices.ActiveDirectory.Domain]::GetComputerDomain()
         $isDomain = $true
        }
    catch 
        {
         $isDomain = $false
        }

    if ($isDomain)
    {
        $MyPassword=Get-LapsADPassword -Identity $PARAMETER1$ -AsPlainText
        if ($MyPassword.Password)
           {
            $Result.Username="%USERNAME%"
            $Result.Password=$MyPassword.Password
           }
        else
           {
            $Result.Cancel=$True
            $Result.ErrorMessage="LAPS did not return any value!"
           }
    }
    else
    {
        $Result.Cancel=$True
        $Result.ErrorMessage="Your computer must be connected to a domain to use LAPS features!"
    }
}
else
{
        $Result.Cancel=$True
        $Result.ErrorMessage="The LAPS module must be installed in this architecture!"
}
```

I will get back to you as soon as the KB is updated later today. In the meantime, if you encounter any more issues, please email our support team at [service@devolutions.net](mailto:service@devolutions.net).

Best regards,

Devolutions Documentation team

**Comment by JeanSebastienSimard** [comment]
Hello again, 

The documentation page has been updated: [Configure LAPS with a custom credentials entry](https://docs.devolutions.net/kb/remote-desktop-manager/how-to-articles/configure-laps-custom-credential-entry/). Thank you again for your contribution!

I will now close this ticket. For further help, please email our support team at [service@devolutions.net](mailto:service@devolutions.net).

Best regards,

Devolutions Documentation team
