### ISSUE TITLE
Mismatch clarification

### ISSUE THREAD

**Issue by kelemvor33** [Devolutions/doc#948]
What exactly does Mismatch mean?  If I move an entry from one OU to another, is that a mismatch?  Will the synchronizer simply move the entry in RDM to the correct folder or will it use the entry from the Action On Entry Mismatch dropdown box?  If an item gets deleted from AD, is that when the dropdown box action is used?

Just don't want to delete things that should just be moved or anything like that.

Thanks!

 ---
#### Document Details

⚠ *Do not edit this section. It is required for docs.devolutions.net ➟ GitHub issue linking.*

* Content: [Configure an Active directory synchronizer entry in Remote Desktop Manager](https://docs.devolutions.net/kb/remote-desktop-manager/how-to-articles/configure-active-directory-synchronizer/)
* Content Source: [/content/en/kb/remote-desktop-manager/how-to-articles/configure-active-directory-synchronizer.md](https://github.com/Devolutions/doc/tree/master/docs/content/en/kb/remote-desktop-manager/how-to-articles/configure-active-directory-synchronizer.md)
* Service: **<b>Devolutions</b> Knowledge Base**

**Comment by JeanSebastienSimard** [comment]
Hello,

Thank you for your feedback! Every time any information changes in Active Directory, it constitutes a mismatch. If you move a machine to another OU, it is indeed a mismatch.

For more advanced questions and to share thoughts on specific product features, we suggest to email our support team at [service@devolutions.net](mailto:service@devolutions.net). You will get a more complete and technical answer tailored to your specific situation from their technicians.

Best regards,

Devolutions Documentation team
