### ISSUE TITLE
Alternative path to user config file in troubleshooting article

### ISSUE THREAD

**Issue by Sparkofska** [Devolutions/doc#971]
For me it was the file
"%localappdata%\Cinspiration\RdpManager.exe_Url_somehash\4.9.6.8\user.config"

 ---
#### Document Details

⚠ *Do not edit this section. It is required for docs.devolutions.net ➟ GitHub issue linking.*

* Content: [Unable to open Remote Desktop Manager](https://docs.devolutions.net/kb/remote-desktop-manager/troubleshooting-articles/cannot-open-rdm/)
* Content Source: [/content/en/kb/remote-desktop-manager/troubleshooting-articles/cannot-open-rdm.md](https://github.com/Devolutions/doc/tree/master/docs/content/en/kb/remote-desktop-manager/troubleshooting-articles/cannot-open-rdm.md)
* Service: **<b>Devolutions</b> Knowledge Base**

**Comment by JeanSebastienSimard** [comment]
Hello,

Thank you for reaching out with your feedback.

The configuration file's location is customizable. The documentation you referred to simply presents the default path. Upon reviewing the path you provided, which includes the name "Cinspiration - RDP-Manager", it appears to be associated with a different entity than Devolutions. If Cinspiration is your employer, this would support the idea of a customized path. If not, then it is possible you might be using a product different from our Devolutions Remote Desktop Manager.

For further inquiries or to discuss specific features of our product, feel free to contact our support team at [service@devolutions.net](mailto:service@devolutions.net). We greatly value your insights and feedback.

Best regards,

The Devolutions Documentation Team
